<?xml version="1.0" encoding="utf-8"?><Database Name="kampusgym" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-UNFIPTJ\SQLEXPRESS;Initial Catalog=kampusgym;Integrated Security=True" SettingsObjectName="kampusGymTeretana.Properties.Settings" SettingsPropertyName="kampusgymConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblRaspored" Member="tblRasporeds">
    <Type Name="tblRaspored">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="botunIme" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="botunText" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>