#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kampusGymTeretana
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kampusgym")]
	public partial class DataClasses3DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblMember(tblMember instance);
    partial void UpdatetblMember(tblMember instance);
    partial void DeletetblMember(tblMember instance);
    #endregion
		
		public DataClasses3DataContext() : 
				base(global::kampusGymTeretana.Properties.Settings.Default.kampusgymConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblMember> tblMembers
		{
			get
			{
				return this.GetTable<tblMember>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMembers")]
	public partial class tblMember : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _gym_id;
		
		private string _ime;
		
		private string _prezime;
		
		private string _spol;
		
		private string _datum_rodenja;
		
		private string _email;
		
		private string _datum_placanja;
		
		private string _datum_vrijedi_do;
		
		private string _vrsta_treninga;
		
		private string _slika;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongym_idChanging(int value);
    partial void Ongym_idChanged();
    partial void OnimeChanging(string value);
    partial void OnimeChanged();
    partial void OnprezimeChanging(string value);
    partial void OnprezimeChanged();
    partial void OnspolChanging(string value);
    partial void OnspolChanged();
    partial void Ondatum_rodenjaChanging(string value);
    partial void Ondatum_rodenjaChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Ondatum_placanjaChanging(string value);
    partial void Ondatum_placanjaChanged();
    partial void Ondatum_vrijedi_doChanging(string value);
    partial void Ondatum_vrijedi_doChanged();
    partial void Onvrsta_treningaChanging(string value);
    partial void Onvrsta_treningaChanged();
    partial void OnslikaChanging(string value);
    partial void OnslikaChanged();
    #endregion
		
		public tblMember()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gym_id", DbType="Int NOT NULL")]
		public int gym_id
		{
			get
			{
				return this._gym_id;
			}
			set
			{
				if ((this._gym_id != value))
				{
					this.Ongym_idChanging(value);
					this.SendPropertyChanging();
					this._gym_id = value;
					this.SendPropertyChanged("gym_id");
					this.Ongym_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ime", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string ime
		{
			get
			{
				return this._ime;
			}
			set
			{
				if ((this._ime != value))
				{
					this.OnimeChanging(value);
					this.SendPropertyChanging();
					this._ime = value;
					this.SendPropertyChanged("ime");
					this.OnimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prezime", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string prezime
		{
			get
			{
				return this._prezime;
			}
			set
			{
				if ((this._prezime != value))
				{
					this.OnprezimeChanging(value);
					this.SendPropertyChanging();
					this._prezime = value;
					this.SendPropertyChanged("prezime");
					this.OnprezimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spol", DbType="NVarChar(10)")]
		public string spol
		{
			get
			{
				return this._spol;
			}
			set
			{
				if ((this._spol != value))
				{
					this.OnspolChanging(value);
					this.SendPropertyChanging();
					this._spol = value;
					this.SendPropertyChanged("spol");
					this.OnspolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum_rodenja", DbType="NVarChar(15)")]
		public string datum_rodenja
		{
			get
			{
				return this._datum_rodenja;
			}
			set
			{
				if ((this._datum_rodenja != value))
				{
					this.Ondatum_rodenjaChanging(value);
					this.SendPropertyChanging();
					this._datum_rodenja = value;
					this.SendPropertyChanged("datum_rodenja");
					this.Ondatum_rodenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(150)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum_placanja", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string datum_placanja
		{
			get
			{
				return this._datum_placanja;
			}
			set
			{
				if ((this._datum_placanja != value))
				{
					this.Ondatum_placanjaChanging(value);
					this.SendPropertyChanging();
					this._datum_placanja = value;
					this.SendPropertyChanged("datum_placanja");
					this.Ondatum_placanjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum_vrijedi_do", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string datum_vrijedi_do
		{
			get
			{
				return this._datum_vrijedi_do;
			}
			set
			{
				if ((this._datum_vrijedi_do != value))
				{
					this.Ondatum_vrijedi_doChanging(value);
					this.SendPropertyChanging();
					this._datum_vrijedi_do = value;
					this.SendPropertyChanged("datum_vrijedi_do");
					this.Ondatum_vrijedi_doChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vrsta_treninga", DbType="NVarChar(50)")]
		public string vrsta_treninga
		{
			get
			{
				return this._vrsta_treninga;
			}
			set
			{
				if ((this._vrsta_treninga != value))
				{
					this.Onvrsta_treningaChanging(value);
					this.SendPropertyChanging();
					this._vrsta_treninga = value;
					this.SendPropertyChanged("vrsta_treninga");
					this.Onvrsta_treningaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slika", DbType="NVarChar(300)")]
		public string slika
		{
			get
			{
				return this._slika;
			}
			set
			{
				if ((this._slika != value))
				{
					this.OnslikaChanging(value);
					this.SendPropertyChanging();
					this._slika = value;
					this.SendPropertyChanged("slika");
					this.OnslikaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
